#Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

TAIYOSLIME_SHDIR=$HOME

source "${TAIYOSLIME_SHDIR}/tszsh/.tsinit.zsh"

#zsh plugins
# source "${HOME}/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh"
# source "${HOME}/.zsh/auto-fu.zsh/auto-fu.zsh"; zle-line-init () { auto-fu-init; }; zle -N zle-line-init ;  zstyle ':completion:*' completer _oldlist _complete
